---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-iot
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "type": "ipvlan",
      "master": "ens19",
      "ipam": {
        "type": "static",
        "routes": [
          { "dst": "0.0.0.0/0", "gw": "10.20.0.1" }
        ]
      }
    }
