# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:JQke8FsRHTwkdjMApPBTN08r1RtO3dtay03dytp0TKH9XRoi,iv:G/X7I8fWRNRtKWmLNsfJoqFjyBoHl5+eGV/R2rtK3UE=,tag:iwJyFq9CqIYgmQKCiM43uw==,type:str]
  credentials.json: ENC[AES256_GCM,data:0rUifCJ7KZcHfnqiwvbXGlKdDTRftsM31+ZOWBS62wMcWQntzzFJ/01xUfnQcqwnVF6ayZmrdjtO07gcHnL45oMfwMBoRYeKvQWAALkfEKaUmKEvceVx+PI/3zjJwvcToPWs6wn70sYG2pO/jClkJ3Tz30hmoN2dv3+OJljPZsEi0QcIeKb4uPP5IewqBMcAY15/hThRgJt2NlPYqljWbSqrSR0JYcrXQ+F1Yy8sKQ==,iv:+iZcCdINESvjoTW2I0uG7v8iVFtLlJ2TnVo1zUOo62A=,tag:oWxCWQOu4HrErYAl4Jm+ew==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1upzm4g68d6555nfx3mn2xganv72sxyksa939cnlqnj82qaj3aq3sj998ls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1cVJOTXVLaWtvUkF4akFp
        alhxWExFSkdRT1krTWxtRWJUR1U0dVlTN3lrCjgyOVBqZ2t5TG02dzF6TTN1Q1pK
        R3R4N0NyS1RNQnVBKytyeU1tSHhqQ1EKLS0tIFIxZXI3ZWdRTVcwK3FLTFVZeDRM
        Y21RdEppNXpJQStBOVFQM200S1dqOEUKVEzWe2GpGD1y/A+zygYS7QRlQ8pksbq/
        3eH3xVY1fSan/K4nyf6CY5cQ6mOLgbliHdMoSiXcRDSGld65MF1qGw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-22T06:47:09Z"
  mac: ENC[AES256_GCM,data:KBDjsAEnH4AklSHSm3j9I8gkDaho/kv1eXLfw3q2csAQghRfWLJQlf7/KVLXG7L3kxs9L/xpCA4Cdf0jFBQijv5MajkYcPP0JivB2BCZeI2+Uxom/ccygC8GTCp+2FNDajoZlYLItA5Smrbs0ImtJdO2cm3ZtR63cRB3Zws754k=,iv:rut+LRFVaKMhXm72OIEfuV5wNGVu9sTdvYMPx3JI/D0=,tag:Mmyxg559A9rW2L52YZhR/w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
