# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:qOmwxXYwc2BdSop08vXYi3eqX6Jkl5rr8FzGP4cGAmwxpB08,iv:an9J1i+RRBfpL0vSs0l7mboFyUCdjka2f0allQS10AI=,tag:WRLwQaPndfGSyMEiaCcedQ==,type:str]
  credentials.json: ENC[AES256_GCM,data:O2bLB+NEcmVgQV7Hr5SdWIfgPnohqPUV5PhM9GhLuthx9l/M5/OfJ5Qb0DCgDQE60uyKkRaK1xcUmFOv95jmSE0KmFJuG0noph61I4dKR4R7ThvSh/+YjUk99TE+59AxtGs6oYLMR6dut1l4JtnxST7pvf6xZizFprwdnmV1YV/7awncmStlm5vC+JOiKdsdJ7H1KWxrJ8E1op6oYaMar9dwBdxhaFjNTnRyixcugg==,iv:n4dqdVAcrAAikslmBrjEBS+27JNXnfHvjoC42PFsKIc=,tag:lkLAYSpS0hxZknDCG1bt6w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1upzm4g68d6555nfx3mn2xganv72sxyksa939cnlqnj82qaj3aq3sj998ls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVNG56Qm9vTTFoV2k1ci91
        SDJSZk95WDYwcjMvMnExejhjdHkrQTREOWlNCm40Z2lOaGRkZVJ5TG5sdTRudy91
        cHFzK1FlR2ZDeC8weWE0ZWRsL2pHVWcKLS0tIDRkUlB2bllRMkRoZ29MUHBrR1Vv
        enAwd3poc3Q3b1pLQ3ArUnUzTlg1RTAKq1Okj58UgEmbyni2iIbcT+SYaIatEo8n
        ThH5c/MfktGWqngWNL72kHY5/IwnuvzIkPZhcWC/AelbeWF2wmj5Jg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-12T08:48:33Z"
  mac: ENC[AES256_GCM,data:yozhVHsTzVkSCu48pBic4kag7x29gFlwukwcasueSwnjKuCZqN3VklDRis8pu/3ICGVYFf1ZUQZDMu9ZKTkX1Kq0DKctuIGHVBV/866k79fOhjuWWJ6gi2ujLX0L4jXpFppBPDh+tsu7F5IyMMk7ylw2eHCgm7UsQvd17y7JCDI=,iv:LJLjz8HPOWelmb2fKOIOV5BU/giKAs+/5ZNDs10ZffI=,tag:5wlpD3G/EoTvSf+OS478ag==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
