# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:AybK5cqJmk2Mig/4LsSbDE8MFOpKx01HIYH94WtlERg+6M0a,iv:TZ4h7XTam90BoYtVQMrXB6NEvJQtalRIQ7f9gkewVbE=,tag:v+q4SpL9ZAw3tlfzmrdrdg==,type:str]
  credentials.json: ENC[AES256_GCM,data:UPeIvyVboOmEkjBnCMVCqIpThN13CrR/Sil8p7ognyA1UKilZfA/w/5qEIwcZ0uSlCEd4qSuFOKoyGQLZnLzg5vQkvdIXW1ZjtoA7mw0JTrrwtK5EmzjJmRMUZse7iZjJ0//Bk37VBrL1IMfwNa/ZLxybfCPcyqY6AQf6zQPhRIvGjj5M5mJ+Dqmyj2k1xbHDEDXfwVFCrjJk81MIKfp3MM0c61U5SP3wR/cdj0Zyw==,iv:Jbwk0jUOBNyiLncePnOZB17o2YYwenW6UN9TLkRGC2s=,tag:+iszU8kg4CxwFnSu8TDqew==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1upzm4g68d6555nfx3mn2xganv72sxyksa939cnlqnj82qaj3aq3sj998ls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoU3h1bUQ3SlVYMlJubWxT
        SlVrUkRibFlJamdlVW54Qmc2SVlHd0puN1Y0CjI5UTNYdWsyeU4ybGdjSTVlQmg1
        ci9SL2ZVdWwydW5uTG96Snk5MnYzQXcKLS0tIFJNeTJVZnJVL0F4TGc3OUNSdnM1
        aVBnUUIrTXNiL2xmeWgzV293SnNvWWMKZEViikOqLlvijMhuW4rh2YdZ+4L0lr//
        rWTRU8M5K0QLfEDskKy53B03m2/f+8eQdT6kxlUr08vEZ+cyvC7e7Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-13T08:37:04Z"
  mac: ENC[AES256_GCM,data:Q/ZpV08YT+qaR+sdfN/3bsqsk3yAiM8Epz4I/ppRf9i+zVaWriHkBU7ExXx1n5fCr2B4PXFM5HTkoNafsV1QDhovrIMusSGnce+xA1xMUqatVL+kUP6nyZAvFjwXEVZOsT09UE4TVctnjhhGekv1XdmHDi8N3f13HOR2nJGtVU8=,iv:nyekvWiF2zVrJ1lILfB5melFCO6Zq2hzT5EC4+DnY3E=,tag:5pEUz3Ze/lwna3hG23mI2w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
