apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: whereabouts
#  namespace: flux-system
spec:
  type: oci
  url: oci://ghcr.io/k8snetworkplumbingwg/whereabouts-chart
  interval: 1h

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: whereabouts
#  namespace: whereabouts
spec:
  releaseName: whereabouts
  interval: 5m
  chart:
    spec:
      chart: whereabouts-chart
      sourceRef:
        kind: HelmRepository
        name: whereabouts
        namespace: flux-system
      version: 0.9.0  # z.B. 0.6.0
  #values: {}
