# ---
# apiVersion: source.toolkit.fluxcd.io/v1beta2
# kind: HelmRepository
# metadata:
#   name: bitnami-oci
#   namespace: flux-system
# spec:
#   type: oci
#   interval: 1h
#   url: oci://registry-1.docker.io/bitnamicharts


---
# yaml-language-server: $schema=https://k8s-schemas.bjw-s.dev/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: whereabouts-chart
spec:
  interval: 10m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.2.12
  url: oci://registry-1.docker.io/bitnamicharts/whereabouts
