# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:f7B0VM+zPzLETzI8WRThT7CMN753nirPd4KYjVeOKhM=,iv:H+ZuHVYC91Jf1c/z0vSNfjtxwWOcwnowN4mS6GVwb2I=,tag:GK8cw+nJ3Aob+pZ56rmbZw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1upzm4g68d6555nfx3mn2xganv72sxyksa939cnlqnj82qaj3aq3sj998ls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvaHRMR3JvWXRkKzJWQ3Fi
        UUc4dTFTR0RjOGlwTnNmL1cyUW4rQkorTkg4CjRGR2xPVUs5ZTVvaFJ1ams4dGVl
        NG1qYkprcXp1Sk80MFY0aXZyenNlSGMKLS0tIENKUmtRcjFrWmhNdnJkbWw3SmJw
        bklCVVVoMTRvL0tmZzJ2eG9kWkZya0kKlLIR0W63oLcD5jlUelAQsUtlZsWDLiGO
        Qh5vOphrCcApAoTE/Rc/IpAMbRcZn+iqG5u2lVOLc701PbRBm97byw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-12T08:48:33Z"
  mac: ENC[AES256_GCM,data:X4RPb7024nAHa2o+dZvuttNf5tEs83tFEq4/BqRdvlBZFZcz72v9JuJEJDjJREP6VcLZKQEhwcAII3qte0VdLA5RFkA5ch07O310kihrpLEjNpVwAkF++MJQObZdUCnGqqKq0hcXAAiXfu5vNHpF+DzijquKRpluycfGK5+hMhE=,iv:aYT56NDV4bXltUuGJfVrmD3IyYD/EOIHgxt4NN035UU=,tag:/KCEaBgwlmjRqKikwfunAA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
