# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:sTxvPxzHGkNRV0tKK7lWcAoKI5gjvwnURiZq4FIJDdg=,iv:xLJ38Oj2Vlk21btbSlEG5nvlzBSPTClaDu4yVflCJXc=,tag:RAqI9kDWrvNsdEytcbGa0g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1upzm4g68d6555nfx3mn2xganv72sxyksa939cnlqnj82qaj3aq3sj998ls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVVFsRWlYQnFNbXd2QUtR
        cmxWQlMvRmJVYkpzR2pGejl2R1hTaEZOYWlRCnlJK3RkTkZyZGc4RWx2SkowazRx
        Z2lBVEJ5bk9oNENOb2dERlA4dW0vbDQKLS0tIExSUDFTTDdqQWFBdDNWM3VwM3Av
        VHpZd1lMSE51MUJjd3hUU1d2SkJCUDgKklAQczmWYhm3pYpiwAZTRm1VbsgCnFMi
        RwPoNOaSDEy+rnbTgHgK1BXQtc4ResFwaXu+O/cFGcVikcxUf0QSzw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-12T05:52:30Z"
  mac: ENC[AES256_GCM,data:YoL/yGI1F2gTEHJuldBb8dZeRcYS6IuAuTP5LXLbWSkax/3IauLoXjNCI+caHPZyx1kRvSVER7Da7WHTKDJL40ugzAV0GMxgKRw92KVUSCFLULdiVKK+JMFzJbirWTOV9GTEN4Ija7gQXGKSxifzHrah2rMGLFwh0QwIao7WT5I=,iv:9KFtj/U/84K8EFBZwLlRVRVtdjh1SPI2qLDvgAN8Pmo=,tag:OjDk/hhkdkqvg89ESAKjIg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
