# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:gI9ioWqagyKekTiMUUzVp8Wr/Xl+lQKh0wP/nb+O6Us=,iv:pqLhxklNIqva9F9+HoH7hfRzq18tcnylUNVv00Obdis=,tag:TQYMoeZlyYwgqr7TiyGouQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1upzm4g68d6555nfx3mn2xganv72sxyksa939cnlqnj82qaj3aq3sj998ls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQzluY0RrYmpxVlZkeHdX
        cUJtUnFMV1QwN0dCSlJLT05CSGgxYngzYnhvCmY5NWpFTFg5YitlYVZEZmQ0Q1Zv
        NWxqTlBFSjBoRlloaHJ2L0RpZVNwMVUKLS0tIEZSUE9YdzJORG5NNG5rZ0tnZVlW
        TEJGL3V1MnJuYkFETnZrbU5nSjRIV28KaRWofIF3fETsJuDvFK8hguzJTeGPipIx
        U5vfYyhyuOv0ILEe0L7uql32TezForznVYDcE1y/737elLd7Eu7BIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-22T06:47:09Z"
  mac: ENC[AES256_GCM,data:kU9kv+sUkdE8Gp8dMy/MMWAjEJekZJCIOke2A6pTUUkQbU8h3cSyk0rlsNjzOqSIOqWNXFMGFImTpBiCSP7aYZxnYX/8CW0K170ieIS0BpCjiL1H7RjwSvO/eb6ou6D4+8VOeI6ygxE+TMgKkiKuOLvrYZlGbS4vFHXl2txI8No=,iv:i2OCIBYgqBmFwOrwix9oTpZt5Fr5WVJfhYfbm7izk4I=,tag:3+/z0/lu8lerKb/37WEDOQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
