# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:3pODj5rsUNQ3l1MZ9zZuehGBLLXTHH5ReTn4bdHsCjdHJU8ZbIDyFA==,iv:sixPCLzNZOaAQHUeFj+73jEBzd2qYTAvPKjCC4xOrUo=,tag:aiNgk5YI/6/QkxkT0LW42A==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1upzm4g68d6555nfx3mn2xganv72sxyksa939cnlqnj82qaj3aq3sj998ls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzenZ2Ull0NDl5VmVxUWZv
        RlhpY3JiSi9FQWpXSTlCMWEyREVNR3dJekNnCnF6cXZOQU9ma0V0ZWowTjVpVDVr
        QWh6MFJxZitIZlpvNUJXeC8yeVhhSmcKLS0tIFlRQ1dIbTdnUXIybi81UjNVOStT
        V2pvQThoc3dFVThsMlA4aFI3cm1qQUUKNgvodW2dIxS3hcbIIfnjrnJL0HRW6N6M
        doz8pCKHCJHq2vr1VHet/d9BCmaus4/kBB+EbRtyoNfGP/33EdoVGQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-11T19:55:54Z"
  mac: ENC[AES256_GCM,data:7TO/dDgT90HCEaO2LVKqrjjQpXnYjD9lTDuQknL0BtuyGJS8Ukw/68jy2KGgfO8UFwZ//NPqJWmpU5+I2u7OhOe10I/BJ+Uo7+AmSlXME/ocJkxHnw0f6bTazlb/i8DuL+xa0zu8mfnJHLnnp7tHiZhNthhM/DBs4WrainQyiK4=,iv:qK+KM9EXKxOYYvg3fn2NV/qXCCU7U/OTyg3/V7o1hNs=,tag:M9p5MeUgmMxkKQr93Pkj6A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
