# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:O0ECfhhhdXNjgxpWxLHn9XPLSd36tpFZWSsXbSHVXKs8Rue75dul6A==,iv:BPrbUvvogpYuKiwB93InkiLpzJTKhT+B/DRtsMrGA+s=,tag:qRAgN4bODas8Asyr0DMuOQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1upzm4g68d6555nfx3mn2xganv72sxyksa939cnlqnj82qaj3aq3sj998ls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YkdNalpxSU9obURzVFh3
        TnNFUFJaUXNIWFI0bE9BSFlIRmwwdnNvMlY0Cm9oNkxBc2d5a0JrdUdmM2d4cmFo
        cC9sR2NoRzRLbS9lNHN0TDFTY1E4N00KLS0tIFFXbHZndjNaTHBQS0F2TEZmdnph
        M0dDSzR5Zm1TTlQ0NXhnbmxJaWJEbTAKH2FBRA2p/PqsisEaENu6FZIQSodwDwRj
        ic4X25/jcHMd1LshjKcnB1rARF04FmXBD92+37X8vs6Q3jROoSmf1w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-12T05:52:30Z"
  mac: ENC[AES256_GCM,data:w0mM5YWae3ulT55iEcB+KH/K5jInziryRD55vJJJcMa/DE/uMlmP1jSS8wuPVhh4US/yIJf5cnWdBHq0I8kYAs1wVIhE04AV+retP2mZVG8jmfTn2BaJH96YTy7xfckewh1M40HyQno8nxxNZcmphky/N2H8qSdkk/Mgfi6If9E=,iv:7mLtmOqsA6yayinV+JHU4bsb9XFmdOii4iL0yIWE7JA=,tag:rhH97k60tFZINynSqC9zng==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
