# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:d2MvsEmlOVp/mLvxszrEidkgu2aO/wS6YGh0d81S8anHV7FwFUyiHw==,iv:U9U7qe2mfEAD9unhIGXFLJFu7pWSk/8ZZ7lbvPz+thM=,tag:zFghB2mubrJ3nKmlcklBzw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1upzm4g68d6555nfx3mn2xganv72sxyksa939cnlqnj82qaj3aq3sj998ls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZEpoMVR1RXZKR2Y1alJ4
        Wk4yWHZKK3FwYm82N3JlZFRraDZ0a1hac0ZFCitLcVJzNEMvWXFpRy9iQUZ0NXpI
        ZkZxNHE5c1FGQ0ZPeExaOElIbm8zdjgKLS0tIGYzNjRiWm9RZTZMOTBwVTRCWXlo
        T3BYdk9wZ0Joc2xDNDRsS2ZrV3B4ZHMKKbfkLoBpg4rqhg5XO5pfq0GV/YA/XY0M
        o0XhcyzMlE32qtupyfPeeBLDKXVx+SF0PhpIVIMGkTF9xwPwILzQng==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-12T08:48:33Z"
  mac: ENC[AES256_GCM,data:kDust5Sr4GgajYW70B++0+Zv3JBTt/UOE7Mdjq0NYHzrOB4573TTrXDUi32z2KlUULlLg4D67rF6055DUQhC/6/Uiv5yWFni8ihcwVkLqPfQmccxeb5BFDhammun3Ed2kOju56OIrh6XyJzv60BXhADpa2j7oJo6q5N606QqABc=,iv:WaT94DbgoeJVcJCVVt2hEJOAJPUePwTB+DSwNMkyOX0=,tag:1VG3WxyMDLs/MIOPcZ24oA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
