apiVersion: v1
kind: Secret
metadata:
  name: cloudnative-pg
  namespace: databases
  labels:
    cnpg.io/reload: "true"
type: Opaque
stringData:
  username: ENC[AES256_GCM,data:6BsAklsHEP4=,iv:83osYPvMThZQYHIZ74UY7Zs/AGRwbEevEAENLP7+G6A=,tag:ANvsNsL8P+XRPcna86a1rQ==,type:str]
  password: ENC[AES256_GCM,data:RJDQGy/rNSfsjEilPMefVTFkzqzCTaCnTwzeJA==,iv:/ji9LUAg28SppdBwu3cBmeASRSYQpTBlfpmqbfkkMaE=,tag:Gzlg3FaxxFVs/m2lpiZCrQ==,type:str]
sops:
  age:
    - recipient: age1pguzgl6ueghhdzlzwelhl9asavxnr9jytr82mcarhswf0gw39gssvhcccm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacnFnOTQrdUY0RHNIRzRi
        UlRkZm9rRzkzdjlIME5wQWxnbllhM1JVU2lrClh6eTBWU25sMTZhUm1ZdFhZbU9r
        SW5rbSszcFhMVloyRDFGMHNJSTYzOXMKLS0tIHdmdWVONHBOcGw3VnNqVFZXbmk5
        TmY5UGdwQ1EwUFFubG9GVktoS2s0QlkKkqMvQ6bHPSnlk/N+5OX5RNsygAtOqAFa
        IOHOH4Ew8O9a8WRuEeZrsAX/gD7vxVhYbCDmmMd6YrW1RhKAqI1ZnQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-14T18:46:06Z"
  mac: ENC[AES256_GCM,data:vCH6OsQiidaPx7NDcXMMvVuFeNX5DNspBYqimRDZYCFCBgpFwExm4hMIVlf6KO/vB03DPwYnIPn4ggjL3J3CoGQ1r1KcfHhK6tLAAHlsScLZCajmfHj1sCsCNKJw8dArsL6Y0C3f3ioHRx5yNUHAQSEyvZiOTYBRto4q8cTn6I4=,iv:kFSUIFzVve6OfrEOvM0/vc0TEaNo05p5v338YzZP144=,tag:torJW+TKa6bPkVRhrPcnuQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
