# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: ${APP}-volsync
stringData:
  RESTIC_REPOSITORY: ENC[AES256_GCM,data:MA/FljbwJ8lB/JRUYW3J1WFbGcumZK2+,iv:AdOQTh8vEM3gtk1INCNbg1Lff//96VxHXxQd60nmP5U=,tag:DCk3llx1Nbjc6jf6coDR8w==,type:str]
  RESTIC_PASSWORD: ENC[AES256_GCM,data:P2X1+LMu1kSGVg==,iv:3BaVwG3V2gbj+NpmpzL0uTysaYFMyU5f+79X0qXARB8=,tag:zQ8TcdQBEN5IxfWaPJTf5g==,type:str]
sops:
  age:
    - recipient: age1pguzgl6ueghhdzlzwelhl9asavxnr9jytr82mcarhswf0gw39gssvhcccm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2RVNyN25WME1GOE5vdU1D
        ZGRTMmxQSXJ1eENLUEU4ZVRQTVpmazZsNG0wCi9mU1lmajFnK1RaS2RCME5tQWUx
        WFpJSjFVSmpndVZ4MkNKOVo3elQybUUKLS0tIFBxSjBDTVpUUnZOTEJURHhNc0k4
        Vk1zclNDcjUwcHIybkxadmZGa3dmY2cKSXPQUC+4FYWYqKd4c/VPRXNNsMHYF6y0
        YSVt1O5BdIxSyLJ6WHj6FalAosseKr1QWCIPD4lX3CIdQDIygNrKxA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-28T19:58:31Z"
  mac: ENC[AES256_GCM,data:/Uoxd6tjvbLmha38ECqFtpyCuRnk6y6eh9Pb0htOqxVFRIy2drvk+TDF4UCnsbMLXj1ZiQj7LNuhLqQgkP7GtlpF/nEePVJbogEKcBe/I3wQ2cl+3KBLB99L2MT18y4UGgLN7SuMstRXvBZcVauaHVgMNFIbmQVPHvXy55GFUBU=,iv:uohgwaqAmsNUPWMHGSjKnrb6qD2+JXhEl44RSGgMNiM=,tag:2Udf5qGFtcTBRHJhZ6cidw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
