# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia-secret
  namespace: auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  refreshInterval: 1m
  target:
    name: authelia-secret
    creationPolicy: Owner
    template:
      templateFrom:
        - configMap:
            name: authelia-configmap
            items:
              - key: configuration.yaml
  dataFrom:
    - extract:
        key: lldap
      rewrite:
        - regexp:
            source: (.*)
            target: lldap_$1
    - extract:
        key: authelia
      rewrite:
        - regexp:
            source: (.*)
            target: authelia_$1
    - extract:
        key: grafana
      rewrite:
        - regexp:
            source: (.*)
            target: grafana_$1
    - extract:
        key: minio
      rewrite:
        - regexp:
            source: (.*)
            target: minio_$1
    - extract:
        key: vikunja
      rewrite:
        - regexp:
            source: (.*)
            target: vikunja_$1
    - extract:
        key: immich
      rewrite:
        - regexp:
            source: (.*)
            target: immich_$1
    - extract:
        key: ocis
      rewrite:
        - regexp:
            source: (.*)
            target: ocis_$1
    - extract:
        key: nodered
      rewrite:
        - regexp:
            source: (.*)
            target: nodered_$1
    - extract:
        key: paperless
      rewrite:
        - regexp:
            source: (.*)
            target: paperless_$1
    - extract:
        key: headscale
      rewrite:
        - regexp:
            source: (.*)
            target: HEADSCALE_$1
sops:
  age:
    - recipient: age1pguzgl6ueghhdzlzwelhl9asavxnr9jytr82mcarhswf0gw39gssvhcccm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bzYvZ0Q1TFFVRjJwNGxZ
        WGhiZjJGd0gyYUYxUmQzU1AySDFnc1NkbmgwCkh2eGNMd1FlQXVMdnRaS3IzV2dB
        S0paVE1ad2poSU1QWnlnellwOGg3QzgKLS0tIFdRVVJrdHhOcFFWOVRTeEpBTWxC
        VjRyMHY2YXFQZ3JEcHdYMUJHc09LYVUKEiD5n/Jr5V20rlh5McUoqjqWzogE9d7E
        +ugxsyalMAvgOVwcU0P24q56QAUfNQSoNh0Ri9PK7rHlTo8V7d0BvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-05T19:43:35Z"
  mac: ENC[AES256_GCM,data:M4iQBoTEFKEhMWDHbIjxZpmvM9BmH5r1gzQzWhNLgYH7epv79K4cAUyeBJ4aB+2ADvTowI98mmzTE05xpWXk7tBMKep+0dVOGdc+3M/8S6W4LFuBaz/0kkrTpIHnqk76ZdFhsBq2EaqgYXpJhd8iHl4A8XaT/u4Cp3quFIP5eCQ=,iv:pK3xVmpu4mgM86QJ4CRiVaqT+DCv36wkuJOLhy3BqBo=,tag:Up3KHj2grAnpHOgbCyA+Sg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authelia
  namespace: auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authelia
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        #ENC[AES256_GCM,data:EjZjnw==,iv:AtzotVGd/5IybOT3LhxlFYkw1MgswwNmRChkkjvHg9s=,tag:lS36WTJDY9dJxBVkC4FU9Q==,type:comment]
        #ENC[AES256_GCM,data:rWHMwuKatYHMPvne/CX+OzH98UflEcslCjRP36i2XHnZ9fxamD6fZXByAMrT2pkLKf5zTrPZvC1Ot7rYqobsZ2Mclrr72V5XnsLcmvmbNJBSCBJvLu1YF0sb4+BS1s2DCWgp,iv:HwiE90VhyXHNIRDldhKFFBqNXy6qrn0ieX3P83NE4HQ=,tag:Fcktr/kOATGndAC8tXRjRA==,type:comment]
        #ENC[AES256_GCM,data:jPvGE2NR19nXSThOq/vFTd0bi8maUn14cOaE4x/jQfl3KJ9Tl6uRLrtc9r8b7AvXPdS9OSr19xRCRwWnuuGaqh5XMLWliTKtY95cYO+1d0wlX5X+KxNxFyuYGpNdgfxjV19jCzopdn83VJmZYSEFnqY=,iv:yNTksB2T8NMjf+XMs9DrsYDZcO6OfpKkWGSAk7CGh8E=,tag:01dNsvtY4b+dYrXXXwsvtw==,type:comment]
        #ENC[AES256_GCM,data:MTZhOl8fivEmCmXbe47PFC41XT9vQE0DB4IE87Z/G/9wgVeAa3fTepqPA0c855xI2Q==,iv:+4FqO7aMGm5JsWMnXUCTm30AlRtte2lTuTGoZIFrqj0=,tag:Y4jyGOew15aLWwy89QzgFg==,type:comment]
        #ENC[AES256_GCM,data:BQx0E0RfVq3vmgX0lv9viaOf8iyDy7/cP0h6s7YPnF9qxVY3j29xakcbA4eIjCfwqAKptOy8apQY,iv:VnMmxvL4N/pwz8zDO8G1mWgfB9KmX2myx+MN9aTYfhQ=,tag:WxMAEN/69c/xf+rmmtKn4w==,type:comment]
        AUTHELIA_STORAGE_ENCRYPTION_KEY: ENC[AES256_GCM,data:8UkQohOLNW0b2bK/AvV/PeQLhwRDGfYm4QEb0SrQgQBbPnQx9SA=,iv:lGhKfyPL5qjtFsaSbnwWhHjevKV2nnWttE6yJj6bv3Y=,tag:Z9YcZehkrN5/JmOSm3JhBw==,type:str]
        AUTHELIA_STORAGE_POSTGRES_DATABASE: ENC[AES256_GCM,data:Zikjpo3OEmA=,iv:N480s4tYG9buHqQsQp6qa52PxhmMQ5VnMSyWhlfyy1A=,tag:TNoLAOlxnqOSnwkeqCtckA==,type:str]
        AUTHELIA_STORAGE_POSTGRES_ADDRESS: ENC[AES256_GCM,data:ysCEl1xJ6mpFfTYw0/gqKQJJI4Q2A+V9X7LqdmAFfHOgj+rH1BJa,iv:QFwBstulNo/wDT9Isr50CoB17MoaeTgBNlKgivzqtgc=,tag:tVMjAvMaJFdSHPrhUSVn/w==,type:str]
        AUTHELIA_STORAGE_POSTGRES_USERNAME: ENC[AES256_GCM,data:Nr73lZEw7z3fZ0C/mkfH02smfIyPHSSZzqmnMX6/kI2nVqkWB8Tvj8k=,iv:rxY6kzKaRSDF5/Iph8hcnme58hRttUEBwgrkTjqmUqY=,tag:txb/ykanNP/fj1Ilw6zBbg==,type:str]
        AUTHELIA_STORAGE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:axFIanuEsApg2oUvBhcWIOW50u6dI0WunU0Z2oz9/QSTYRzRtB+Gmb8=,iv:8itsknk2UMBAU6nmOJgquBMb5P8yO/nm3udRG9cbfQQ=,tag:yHiooMChQ5mVNWQzCeHR+Q==,type:str]
        #ENC[AES256_GCM,data:oKIK7azYoSidoG1ovxM=,iv:g4nEIrCwShvdYVqJ7p9GkN2bYTU9zY12vGirEo0jNBU=,tag:kcXrTiT+fCR3nRv8TcCYmA==,type:comment]
        INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:JYuIBznrtro=,iv:C8oDQXSoH06i4bYMKjwtlIBWWSVi3GC0hNAwJx1wcJI=,tag:H0f9xD7bG2Wkg3svFKw7wA==,type:str]
        INIT_POSTGRES_HOST: ENC[AES256_GCM,data:mjwL2nybSoPUlaHo6WQWNLfsqhx7m4oisrG0sQRJgsnhq8hX3spX,iv:Ja01rPD1YxZkGT04pZELyLlszbVhE0ln20AUYMRrirU=,tag:r9HNmOwJP29iDhoqIR8PIA==,type:str]
        INIT_POSTGRES_USER: ENC[AES256_GCM,data:JKWXtA72Uf5k7mTdkL+JcnlFgcCHknhOO4x4CZXXcWjLo1jLdHaXmEI=,iv:qGehq5cst+eeERqYI4TvMpp+2AUrr4Gwkotr0zj09lc=,tag:J/UVQQPVZGAoQkFksbdHYg==,type:str]
        INIT_POSTGRES_PASS: ENC[AES256_GCM,data:aPuEkvi1q2I5gpqkTFoB40dmHuP8yaKoVYVybhYDbeHzlTJ9/ZDJwOk=,iv:EJXWgDGeRYdZ+W8QB2StuV/FoAzka7PbSTaEnJXJ5dc=,tag:bwUiYnGfoaJqDg0i2qYFNw==,type:str]
        INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:93QhKIHlRLIpi8N0gY1WgzeLnhaQ+gMDG8Y=,iv:MKnmRjg1nYpp6mKRrsvaCjhOmi/bKpOTYrVL1O9F+sA=,tag:eABKW/AnVuTSsW68bqfpNw==,type:str]
  dataFrom:
    - extract:
        key: authelia
    - extract:
        key: cloudnative-pg
    - extract:
        key: lldap
sops:
  age:
    - recipient: age1pguzgl6ueghhdzlzwelhl9asavxnr9jytr82mcarhswf0gw39gssvhcccm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bzYvZ0Q1TFFVRjJwNGxZ
        WGhiZjJGd0gyYUYxUmQzU1AySDFnc1NkbmgwCkh2eGNMd1FlQXVMdnRaS3IzV2dB
        S0paVE1ad2poSU1QWnlnellwOGg3QzgKLS0tIFdRVVJrdHhOcFFWOVRTeEpBTWxC
        VjRyMHY2YXFQZ3JEcHdYMUJHc09LYVUKEiD5n/Jr5V20rlh5McUoqjqWzogE9d7E
        +ugxsyalMAvgOVwcU0P24q56QAUfNQSoNh0Ri9PK7rHlTo8V7d0BvA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-05T19:43:35Z"
  mac: ENC[AES256_GCM,data:M4iQBoTEFKEhMWDHbIjxZpmvM9BmH5r1gzQzWhNLgYH7epv79K4cAUyeBJ4aB+2ADvTowI98mmzTE05xpWXk7tBMKep+0dVOGdc+3M/8S6W4LFuBaz/0kkrTpIHnqk76ZdFhsBq2EaqgYXpJhd8iHl4A8XaT/u4Cp3quFIP5eCQ=,iv:pK3xVmpu4mgM86QJ4CRiVaqT+DCv36wkuJOLhy3BqBo=,tag:Up3KHj2grAnpHOgbCyA+Sg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
