# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:SecTyjCpG6TFXLXG7ax8ybcT2ZotF0m/ja5EjRjO5Ug/GlI3gPIxNQ==,iv:HtMauTro8aAKV9aaF8T0GNW4/DJ1+6uLngVpidkwVpU=,tag:RrxOOynmEK0SIdwBmKw6mg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1upzm4g68d6555nfx3mn2xganv72sxyksa939cnlqnj82qaj3aq3sj998ls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1Ri9HQ0kzRmZFTDZSWS9m
        WkIydVNaT2ZlOHJGcGJQQ3JBdUhERDZ6Z3drCjRBYk1ZOFBEaWhSc1FqM1FDRVhl
        cTNMa2pPS0lwR3d0SkZtcGZoUEdpQjgKLS0tIHpkR1RJVlpUVFpKdXFMMEQxbG13
        UStGTWJ5ZTY3WHU1TGVjb3VuSHdFNTQKlFw24GafgaiZSKEBexcuFkcwxtDiVgAc
        P+CAQ7QuqN2TNnOhVvBN1HzqojsFsh34dCrmIK0RkRyAvuYYNkYJAw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-13T11:00:05Z"
  mac: ENC[AES256_GCM,data:co9yE9bvprfWM+TGj7zqT3o+251jdFN7TfIX2RGzN2a2wXLR4ONIlOAzLDA74PgKIikFlGaipxs5147AUUTEbIeNmReFJYY3XHSk55xRnHMrAQxt+PhF4ugVb0FdXXh+wxJl/f0PPCWG9g9yPQeT2OaldZA9ne+XHb72Z5sNdtU=,iv:AYy1YxfbrbBgBN0UvRCezzh81wkntpuUYpOnNn5hneM=,tag:51rTOkVcpPaFjwQ7x4PWhw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
