# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:JZadT6vaOkGAx5xk4KC0vyr1o4oGhNVMTPG0unLrbeFK0HUXOZ6uaQ==,iv:OxzTzHrU7W4loOv9bZqFQgKpdx4XsvR/jE88m5hafTk=,tag:7lzJg664Xsoch2f81RXtcw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1upzm4g68d6555nfx3mn2xganv72sxyksa939cnlqnj82qaj3aq3sj998ls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NlUwWCtFNVRIb2dRTzg0
        NHBGUDRmakYzNnd0MG1LalBYSzZoVFhiRHdvCldZZGlVRkpjT1hUTURHSERReTI5
        VW4zeFA2Z1FJaUN3MHlkNG5ZeXY1MGMKLS0tIFIvOXlxcjBTQlRpTVJSdlVsUGh6
        cVViaHgrc3JzSjl4TDZsTC8xN2lDZ0UK9yWNVlq0KGFzSM5HxQvEXLeg/fyxd0Cn
        qMr3gbbhLMkCvuVldNC8DfOE035oOUFsvjHNNfY5jesedIMLuzV4Qg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-14T15:53:54Z"
  mac: ENC[AES256_GCM,data:72VVd0DvN16OXI+/Au3ZJJmqr/UxxBwCjwAsizBL3Yit1R01OjJYTv9qEV8rQ6R2zQS4IvOpFICsJ91N8/hVu8pvk18nIx9+2MbbJUL/UaJxo+X92LKl9h9+Sgq3dmfioOTP2+PkASmaleKA9KxYW36/x0DJi7M3VryYgBzk1Z4=,iv:1t/D/r6TmysxzWC8wvN6H5XtQxKA4Y/RaKDT/cBi2x4=,tag:9AautT5CsqFhjsevMPz5YQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
