# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:jV2Vlh+qpjlZwA9Z1nPX9WBudyQl2xgUb170but7MxbKa8uW5pdLrA==,iv:zyTisH1CvUizIfJtdwXzK+ohsDZQIevuv654P8EQ4x8=,tag:TrHSqO0Qi5QuqmF9OIshSA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1upzm4g68d6555nfx3mn2xganv72sxyksa939cnlqnj82qaj3aq3sj998ls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEbkJ3TGdFbUZCWnA1eklo
        dHRVQ28zNDdVenlZdllPb0Ixei9hUGZNU0h3ClhwT1o4d2lCdTJqUjJTV21zcTBs
        WnVSam5ES0wyM2h6YWg0WENtT2dhancKLS0tIGhmUGt4Q3YyL2t1bGtMTTRwb1dC
        T1FkYUJEcDhERm9zTm0ySTVLZUVnUjAKjwu/SFaDeZhJPDK5gIZIBbiMCjd6CC8E
        zfpsoUNpMz7HhciVYn2l5cz0+TaqlaOMGhcUhZcQjweM9jkcRUUqLQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-12T08:48:33Z"
  mac: ENC[AES256_GCM,data:MtWgcg6mgLxINoz5gCATbwYgKD1xzcOjoo4KQY5eFFOjGuPilw315iM1/uJBfCXM+aoTxHmeWcNcMmm6v/JVCti+Z6Y1tVYzHTQibxfgnK0FZWAByaygIA0uyoLpZPNmUsZsgyb5yuTf3XV7z4mIPLBRBNYuN49uT4TFE+D8N2M=,iv:Tv6XKdv/B8ixDmCbunVWrFvXrzGHR0pqNiBjev8rfHU=,tag:s0iZObmdA4ooiOwSfbr6lw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
