# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:von6/yN4f/uSF1OBNVOFJew1aUUxNhsulkdxA1EPLSdkzvqdDLjqFqvBQaNovuFdD8oPQnraXQrZyC16hIZ8yJNkxSnY7pJ6LLe7juxChQZ+dFxyTZqBMxTN6Tk0LdtwfQfNdF0M79uF/dWS6L0t+ya2Uxpv6x9AN+OEcB1ETWAWNfT4lfI9RGSS+FIXTJLVtxv2M3ixPDwqQ/nUaSU9EbEi7F0Rd5FaO9lfj6UGk3jiJoRV,iv:CLkABWU7CiHcxfYM5VvraIO6NcvA9oP8oiC0S2Nfxl0=,tag:CiOXeigCmLcsxkKlwL6Yow==,type:str]
sops:
  age:
    - recipient: age1pguzgl6ueghhdzlzwelhl9asavxnr9jytr82mcarhswf0gw39gssvhcccm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuUm03eGhGZklMaWZudFV5
        S2phNCs2cjJNbWpBU0UzN0hTSWZwU3lSeXhnCkpjcEprcjY0dlZCWmo2SDhPNzdh
        blFXcXd5VVJCaW1FWjlrenpzYitCcWsKLS0tIHNoOGEyc0E0dXFCaEtGUUkwM1FN
        QUhUTThBdmk5N21seDZ3c2pIZFNqTEUKp+LN8hCguBVibHa7Z5RbVE5ZwFRWmOIH
        NoIqC/lfmVNX/GSpho99nQtLRCKkLMCxyL+xgGHAgZxVp2vQ5bq01g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-06-20T20:11:54Z"
  mac: ENC[AES256_GCM,data:W6MoZhJtSKXb/3hHJf5ZkT/5idxsEVApve0O5fw3zCtGNOSJtTz51ij6QkaDYVOR4ef9OS4fHeGEAl/ACgvOxlmDZ5nCDgdSsLI4eaYLclUZ7n5EG3nfTq+BK4YcbzrhXrjuXsnPrIivNd0Sl+uZrdG/DvwCQ2qiJboWRGICz78=,iv:f9liFVYw1dnedm1ATGBtgkq2z24VWFbZ6VBznX1PX+M=,tag:JOdC3txNmZJhPEX7GQD6rw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
