# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lldap
  namespace: auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lldap
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        #ENC[AES256_GCM,data:vdsjvQ==,iv:0/kuBqdXu8B4RK8V7Nd+EI2qVALuccO7GoSHxIkHCLo=,tag:PXxn797I7+eCkaxGGXoWfg==,type:comment]
        LLDAP_JWT_SECRET: ENC[AES256_GCM,data:W6i6dKsNYRJsF5DZ+GOAiGAfN83z1OA=,iv:CBhAS0fN/vEePfGE9H+ED6h+qiLFgRSrhmXz84UNk2U=,tag:xVyK3xz/nNja085b0KcVag==,type:str]
        LLDAP_LDAP_USER_PASS: ENC[AES256_GCM,data:6OgMoWiagzx9vos2MWa5Ybygy1XzEXdLrP5Q,iv:Lyh8EpdiOOEbJCLGnZnYqoep8zvBXuzNCWH8p8ZNCLU=,tag:Be8J4zsoPt5P6oB1T5dhUQ==,type:str]
        LLDAP_USER_DN: ENC[AES256_GCM,data:3VqjpwXtBM9jat+9NSbZoTs3IJk=,iv:e2ZbdEVGp8NlHYFsu15rWji/vJTDoJD5PA2J9g3vE6Y=,tag:KTWKJzsiRreHZNdtK+4yoQ==,type:str]
        LLDAP_LDAP_USER_EMAIL: ENC[AES256_GCM,data:1wQtj8rpJFi/PxjBevuexQvE2XCBIoU1Qscq2Q==,iv:qWIspFcKZ2uWTsomZEOL2yK8K78HSoj0jDFGbeC9LcA=,tag:2KnFayNYMAzFilR4WVe/NQ==,type:str]
        LLDAP_SERVER_KEY_SEED: ENC[AES256_GCM,data:gC/ng5/bdSM813OdW5B4PhNT7xdXr34RN7RRkA==,iv:/jak/R/06dt9kCrXNUfUAL2SqwNSNqoBVkH/OcvC4LE=,tag:5Ut9LG4VBsaut/VV7O8J0w==,type:str]
        LLDAP_DATABASE_URL: ENC[AES256_GCM,data:QML9ziKuzYojITn0shCo0byxz7ulxdwlbwVhplqqdBvlgGQa4+b45Yxm7BkM3iIFEy6+uWbkC3cVuo4eVLv5D8NorGondQagC56qEp4CDRd6C7mr64sW5TnFcnvijTMW38c=,iv:O0JnX54JZrzGBQWeyAL5kbY2MgWyPKoXTrE83Zi0uR4=,tag:Mzr03DtejqQEzVjlmL5Ymw==,type:str]
        #ENC[AES256_GCM,data:gAzeWy/dfqalYaxpnq8=,iv:E48vNaBfRz3b9TJOf8hwQQTd4adAMh8WRjOvAW1aOdc=,tag:TzpXhr3Mve9OxslwmFMvLg==,type:comment]
        INIT_POSTGRES_DBNAME: ENC[AES256_GCM,data:J1b4e08=,iv:rG0QNBTjLv2vKArvHon5uqVcobr/1yDRHhdjNsHKMtM=,tag:zrX9frmyoy549Yrt8BwtCg==,type:str]
        INIT_POSTGRES_HOST: ENC[AES256_GCM,data:iFf0g5QwG1M5my1gnQE3VbO7kDxZLf0SiqRuilQFtR3UPb2Q2c0V,iv:gVNAaOPQvtB+e6UHRPWqsBSbe+pfnGJ15xX9DaHnQ5U=,tag:OYWRqLuqgmnQwuvrZ95jCw==,type:str]
        INIT_POSTGRES_USER: ENC[AES256_GCM,data:b8aZbgL6hfJAgb14mzasgBACIs8=,iv:JPlMdxB5zTvHxn3ocLWlkZq9jaDSzbXEGGoFJySkceI=,tag:cdnmfwzqzlJMjeDx1nKP4Q==,type:str]
        INIT_POSTGRES_PASS: ENC[AES256_GCM,data:soU7ieg+CX8fUNQjBOKTE0uQbIg=,iv:SUlejgQ0foGJbH7YfRSFOci1pkJgvSasGViXsZditvk=,tag:9Ha7FW+t7UShPAUwFMnZYw==,type:str]
        INIT_POSTGRES_SUPER_PASS: ENC[AES256_GCM,data:vJfyDk9odmOsnIv9m+Q8N+alg0hEyr7cHsM=,iv:GOCRTuJ/iUP5Q5tU82uPUWa8LyRb0XrvQrS3RP5FHmk=,tag:U20TIu6yoRGkn4bk+2F/fg==,type:str]
  dataFrom:
    - extract:
        key: lldap
    - extract:
        key: cloudnative-pg
sops:
  age:
    - recipient: age1pguzgl6ueghhdzlzwelhl9asavxnr9jytr82mcarhswf0gw39gssvhcccm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TWxzRjJ5QXhMR3UxN0x4
        RDI0U0huaTBWTjZwbXd1WnpDRUhRTXVQdkJJCmNkNlpRRDdsbjc4cTdkbzl0VzJ0
        TytQbjg0MGUvWGJhMTVMK3lKbXUzczQKLS0tIFNiSzVZaHcydTU0Ny9mV2NRbDNt
        OFh1Rk5MNTlRV0RHN2dGUzZxRWdVbFEKNRvMtmhAlHFFViqT6DXq7ykMjaMKFbkr
        EretIimD2S5PCM6iQy04P2t8aNviqg+863RCZPxo7amgLcewXICGHg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-05T19:43:35Z"
  mac: ENC[AES256_GCM,data:dKW6w4muubV9eWBFHnVzaW8Ly7ZRSVQpu18o1k4P2unObAFFYNh61rGB+W5DwP97SpFMk9tZFj+YEJmg58JRu9g877sWiN596B+LNiJNGx+BvfF0wdy7vux66wFAOt8L1yXdDl+aYww3yTEv8YXtI+K0en/Wkokb17UQ+htU2Yo=,iv:Yo8WySAta8zbNBLOv60VQSvefePVArGgLyXNTU28qYs=,tag:TtsWbhKHXpy/p8/tQnDTng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
