# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.10.0.200:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.10.0.200"
  - "k8s.anneken.cloud"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "k8s-prod-master01"
    ipAddress: "10.30.0.101"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:02:1a:10"
        dhcp: false
        addresses:
          - "10.10.0.21/24"

        routes:
          - network: "0.0.0.0/0"
            gateway: "10.10.0.1"
        vip:
          ip: "10.10.0.200"
        mtu: 1500
      - deviceSelector:
          hardwareAddr: "bc:24:11:d0:52:12"
        ignore: true
      - deviceSelector:
          hardwareAddr: "bc:24:11:27:d6:38"
        dhcp: false
        addresses:
          - "10.30.0.101/24"

        mtu: 1500
      - deviceSelector:
          hardwareAddr: "bc:24:11:f0:7e:d8"
        ignore: true
  - hostname: "k8s-prod-master02"
    ipAddress: "10.30.0.102"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:59:8b:28"
        dhcp: false
        addresses:
          - "10.10.0.22/24"

        routes:
          - network: "0.0.0.0/0"
            gateway: "10.10.0.1"
        vip:
          ip: "10.10.0.200"
        mtu: 1500
      - deviceSelector:
          hardwareAddr: "bc:24:11:4a:5d:fb"
        ignore: true
      - deviceSelector:
          hardwareAddr: "bc:24:11:0a:54:70"
        dhcp: false
        addresses:
          - "10.30.0.102/24"

        mtu: 1500
      - deviceSelector:
          hardwareAddr: "bc:24:11:19:b0:04"
        ignore: true
  - hostname: "k8s-prod-master03"
    ipAddress: "10.30.0.103"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:08:76:2e"
        dhcp: false
        addresses:
          - "10.10.0.23/24"

        routes:
          - network: "0.0.0.0/0"
            gateway: "10.10.0.1"
        vip:
          ip: "10.10.0.200"
        mtu: 1500
      - deviceSelector:
          hardwareAddr: "bc:24:11:ad:27:6c"
        ignore: true
      - deviceSelector:
          hardwareAddr: "bc:24:11:7d:b4:96"
        dhcp: false
        addresses:
          - "10.30.0.103/24"

        mtu: 1500
      - deviceSelector:
          hardwareAddr: "bc:24:11:77:fa:52"
        ignore: true
  - hostname: "k8s-prod-worker01"
    ipAddress: "10.30.0.111"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: 
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:2b:5a:56"
        dhcp: false
        addresses:
          - "10.10.0.31/24"

        routes:
          - network: "0.0.0.0/0"
            gateway: "10.10.0.1"
        mtu: 1500
      - deviceSelector:
          hardwareAddr: "bc:24:11:b9:75:e2"
        ignore: true
      - deviceSelector:
          hardwareAddr: "bc:24:11:dc:59:69"
        dhcp: false
        addresses:
          - "10.30.0.111/24"

        mtu: 1500
      - deviceSelector:
          hardwareAddr: "bc:24:11:05:9a:e4"
        ignore: true
  - hostname: "k8s-prod-worker02"
    ipAddress: "10.30.0.112"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: 
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:66:ae:cf"
        dhcp: false
        addresses:
          - "10.10.0.32/24"

        routes:
          - network: "0.0.0.0/0"
            gateway: "10.10.0.1"
        mtu: 1500
      - deviceSelector:
          hardwareAddr: "bc:24:11:42:fa:ee"
        ignore: true
      - deviceSelector:
          hardwareAddr: "bc:24:11:b2:84:a4"
        dhcp: false
        addresses:
          - "10.30.0.112/24"

        mtu: 1500
      - deviceSelector:
          hardwareAddr: "bc:24:11:1c:12:6d"
        ignore: true
  - hostname: "k8s-prod-worker03"
    ipAddress: "10.30.0.113"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: 
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:b0:bd:1e"
        dhcp: false
        addresses:
          - "10.10.0.33/24"

        routes:
          - network: "0.0.0.0/0"
            gateway: "10.10.0.1"
        mtu: 1500
      - deviceSelector:
          hardwareAddr: "bc:24:11:61:d0:06"
        ignore: true
      - deviceSelector:
          hardwareAddr: "bc:24:11:01:20:47"
        dhcp: false
        addresses:
          - "10.30.0.113/24"

        mtu: 1500
      - deviceSelector:
          hardwareAddr: "bc:24:11:93:46:89"
        ignore: true

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

