---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app music-assistant
spec:
  targetNamespace: media
  components:
    #- ../../../../components/gatus/guarded
    - ../../../../components/volsync
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  dependsOn:
    - name: multus
      namespace: network
    - name: rook-ceph-cluster
      namespace: rook-ceph-external
    # - name: external-secrets
    #   namespace: external-secrets
  path: "./kubernetes/apps/media/music-assistant/app"
  prune: true
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: false
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 500Mi
      VOLSYNC_ACCESSMODES: ReadWriteOnce
      VOLSYNC_STORAGECLASS: ceph-rbd
      VOLSYNC_SNAPSHOTCLASS: ceph-rbd-snapshot
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
