apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: media
spec:
  template:
    spec:
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /config"]
        securityContext:
          runAsUser: 0
        volumeMounts:
        - name: config
          mountPath: /config
