# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zigbee2mqtt
  namespace: home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zigbee2mqtt-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        ZIGBEE2MQTT_CONFIG_MQTT_USER: ENC[AES256_GCM,data:FHvAoLGk/s/ZoflB7zhW2C97Y2TOZw==,iv:1+fcGG3TX8+Zho421RzDjpd+nYIgfPNAZ8e7To7wO4o=,tag:cLguOIbsXCr9qcp5sZbAkg==,type:str]
        ZIGBEE2MQTT_CONFIG_MQTT_PASSWORD: ENC[AES256_GCM,data:MKO9kf/ag3uE0ecC8FEGWQOMWuMpVg==,iv:K+NrpQH2f6aCU3lGCVe2+BNUKX+YO3p7q+0cI0ok/Gs=,tag:y/fk+loEksM3zjnNB+T2xg==,type:str]
        ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:LAGgrQBMwwRhEVa1G9WZpJw9kxrDj0WdqUBu/qiZpL7WP9AncqqSTPA=,iv:VgCqMmbWSJsiJnqwURYFolMoAPm/zwbiWPPE/FtPpQs=,tag:8YXAkeWrxRqhbDfvI6Mkjw==,type:str]
        ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: ENC[AES256_GCM,data:rPhvGm4FjFJ70xT6zKOnRtVE6iABMeANutx7uhoVqy06dWS9B3T9d4yWrPh8,iv:uinRw9CbgdBLZkvdDbIASk9j3gSaYgURDhv2U9Ojmb4=,tag:ox9ksD9Wu7Adrp2kX8+3cA==,type:str]
        ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:jo9hvl4CB+v+Ly0MQsMI1n/ZVA/lPqB/z3S/VKjS,iv:f8JDz4qZPMl5H9JqPYgkzhHvHafcOpRse8CFY8xN2m8=,tag:O3HURWWFd8AKxusRWfkEjQ==,type:str]
  dataFrom:
    - extract:
        key: emqx
    - extract:
        key: zigbee
sops:
  age:
    - recipient: age1pguzgl6ueghhdzlzwelhl9asavxnr9jytr82mcarhswf0gw39gssvhcccm
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UWxWWGg4KzI4MmpaZkhH
        cVBSL3JuTGQ1NGlnSEJJcHhGaGdmbzVYSmlZCjlzTjU1ZnRIakxxSXRrUXhscVEw
        cWFiVlZ2RUNtVVBrdytYWFE4cnI4YkkKLS0tIFEvTWJiWFFoaU9CSWVzRitWK0tw
        dEpjZGlpc3Vta25KV080Y3RQVVN1WVEKIxGo/Z/3Ymk+qX/eBRMPqTqb5WY1HfNb
        lBGkUyfmYJTRQ9Ah/D10JaxqBAEMI4hTreHcGWKWdmeDfa/cUDYtYg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-07-05T19:43:35Z"
  mac: ENC[AES256_GCM,data:sAJYIRF5MVq/Gnxng0pNN9bKfKvkvndeOFcwIYUW8040dIAF/pWsb1iupJgr8RYMfAv5aeSp4QfUJjJQgVyS8bEg3la4Gf/rr/lBmiHdhhFRKFCrYARqeGmWWkiJr8eX/u8CrtqcJ1qGdLuLgyyrF2eb35GEjA68tPdIyckPtkY=,iv:5vRoELnNwtlqzBaP2IzpDsAceQxJoEHGU/BZxbzzudE=,tag:LF9dih6Ksp5dPcZaRraUAA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
