apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:KinNh9/h2JIROpPkvw==,iv:WcYw+Y42QH6A/os5fDttFoDZypErA/IIE8v3YN9vwA8=,tag:cLR4RywyCTPvpHviv5MIuQ==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:TeDp+fl7vmwBMGh46S7WB5HU0IoUdWuysM5BHcxQtKeVH72z,iv:LaYbVLirXf0Rqj26k0ZWXiNXfhgdLrkDwgh5LdO4QLw=,tag:Z5wgmUzdqrBf90Wmeo+YjQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1upzm4g68d6555nfx3mn2xganv72sxyksa939cnlqnj82qaj3aq3sj998ls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxNnhzMTYzNDc0Y2NhaGxL
        WFFUUktSa2FXd1Q2WHJBZ3B3cWM2eXh3WUJzCndpcGFWK0NuRmFrVGp1c3ZET2NL
        NldHanVwUUljbVBXSHQ5OFBYbVpxQncKLS0tIHhKZytLRHQ0WVM5ZDZyZUI4ZWR6
        ckpjd25STmNNK0ZEWmxZT3BaQjdTV3cK6p8nP9Mo9o4iO/zlI9sK55RkOUM+ir+b
        XWsmsxDo3PT2Itbng3XKQJ+T8iRwsCmBaw7leB8bOviQ6+I9rkRZvg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-12T08:48:33Z"
  mac: ENC[AES256_GCM,data:WvD+045nryR8W5DmTF5S8ZB3GA6Mv4haNJVxgRkn4cUKbmBLqrvOJAxGzJhZl86QjZfDzpS67TU/1p550H9JXXH8w3ZTvDR3yu04doqlSED3S0xYsVKnIkfiVJQByO5TQlIXoGuKcLNoUB1Z1s44ZWcRBEo2/HU35u5mjhXfQAg=,iv:bW5SbrVwAf+4uihEmQzxnVWVbWkzcwunhIy3BM+RTOA=,tag:CttbXRCz9OvX4uq7ZnwYRw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
