apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:tIqkMnL5VFSxC9JFGw==,iv:SJimfViE0tgY8YbgW4U4aJqiUw/lda4EvUzrCCwK3rA=,tag:u2ZsSNL7kGKnbQx4Kd0/8Q==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:MghDEcRrTG/WHxNIXW6va9MNRgHHlt0uohSp0eYabldHnCdD,iv:6QhURnXuxkQ/6jWGjKphwQmZKW1lj++RUgmRAEmmHgM=,tag:5YzvF+vu2VTvBI4YO6Wlew==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1upzm4g68d6555nfx3mn2xganv72sxyksa939cnlqnj82qaj3aq3sj998ls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWYndYWm9FNDU5QUM3cit1
        elpZZkxMWkdxdE1hT2k4VG9FM1pTNjg1NTFRCjFObEpXU21qUmVmZ2puOTE4YVVq
        ckh2R2cwczZuc1BjOFR4Rm45NkhtN3cKLS0tIC9OQ3VOeEFHWGRhOGlZeFBQTTVx
        dW9ybmtvZkNNVXRUeW91TTZJL2dvQlEK3DcTmyZU3KyRfXAMMYf4SOXjVWkVgrd3
        njOaRyIjvnI6+8VKqK/YVKkKNaPy8KOgECRWPIGN937QKbTADPTOQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-13T11:00:05Z"
  mac: ENC[AES256_GCM,data:d8anBrV2QE7heh6xrEM9qKELvkPzTP8HBwJX6/VvNE78rqgxC0bnhs0cgygZ/RV6+AOheHtMPE3cG5IMfjzaBIsCd5IutV/llhUVdKwtV6Xg8q74+OWSULH7Xix9ZW+TgR0TWbupqYdTwMNfW0dbASnA08tbOkoScUv6ZU044M4=,iv:zvHImy+lBRZLy3ljh3guoWP5DcpcSh6nHya9o8FZl+Y=,tag:1oabgLqMPjBceNERSR7ORg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
