apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:EBimypvkZ8DA2Z5jFg==,iv:c3xVFs5D/OCwMV/I9V/KZDaPUVA9vZ8pjwoaXwswtjQ=,tag:EedZ00UsSPRjkfGemhpR0Q==,type:str]
    SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:vmqCvqnjcKTEjot5hGQdMt+UwadwC8sVcZhtdikkgsBLFHqp,iv:ooIbfIQUX7objAo01ghL6+69/3NeK11DI6715DuSDsA=,tag:gck+xi+DhEW0oH5+g26xNA==,type:str]
    SECRET_ROOK_EXTERNAL_FSID: ENC[AES256_GCM,data:+T6BvO/e2lH2m7h8LUI/DeSNis43SWunRwdXX8QBxHbpDfHV,iv:xIqAeOzHwvOh637NXOTZIJQaiJlJkq/4HPdRquQzwu8=,tag:F3kCbkuUaOEhsWoVzuwK9Q==,type:str]
    SECRET_ROOK_EXTERNAL_USERNAME: ENC[AES256_GCM,data:4fUMge8WzeSAXyvLhbfqLsbyfZM=,iv:oshtZB25fPB+tpO2slqxaQFpbYZ18CvM+bI46pWe3lQ=,tag:ZDT+fGvuKE82XyevQe1wYw==,type:str]
    SECRET_ROOK_EXTERNAL_CEPH_MON_DATA: ENC[AES256_GCM,data:nzWPsF2iBjEfQgRAv00IKzgPVMWh,iv:Y1UhRFzBMw2rQKEPJXsHwt+k1j8+1gd291fYcPvlxrE=,tag:Nms6sTaW3QiX5bSRl8aWxQ==,type:str]
    SECRET_ROOK_EXTERNAL_USER_SECRET: ENC[AES256_GCM,data:70iWldczhr/C9rzUWWe644LG/4JnBrr/RoYwEXbQ/HJbDKOeSaAC2w==,iv:7bMgCJ4dOrIoRJji60q2xEBRg3Xa6oENTowhZTnU45c=,tag:JeRj7YrpqYGBsmgn5JOs4g==,type:str]
    SECRET_CSI_RBD_NODE_SECRET: ENC[AES256_GCM,data:Oidzl/2xwrrZHj8f2p1FU7192isx8litE9OEsjNnvRfWR5YM9kJn/Q==,iv:FkowEYXdMc+rKLxMSyZ/FimAfJkjDRACS7bj0RfZ0Fs=,tag:NXAu4gAIx42VJdOGB+lthg==,type:str]
    SECRET_CSI_RBD_NODE_SECRET_NAME: ENC[AES256_GCM,data:9ht0LKiEnzFkx7Ba,iv:V9JHsr8udU3fIot+68Ek4ALsTkQEt67SZpDbI20Oy1w=,tag:UkHT7awexpODtwhXLSe/TQ==,type:str]
    SECRET_CSI_RBD_PROVISIONER_SECRET: ENC[AES256_GCM,data:BdkrHoEYc94gaXHzx4E6FYmfmoDTklUjXydxjkNdrsE3Y1giHbcpjQ==,iv:TPs6PQh9iB8LSXyKc3+RQx+PCcbDSbKqLZnbOmG8VDY=,tag:SmjLQagJlr+Mk+YBbV04rw==,type:str]
    SECRET_CSI_RBD_PROVISIONER_SECRET_NAME: ENC[AES256_GCM,data:frmlzON4duX7A2LE+HzTP3IDHg==,iv:RUon1kM3NGI6363BR3WTOS8Soy75B+2Z3LQSsBoJ3Do=,tag:oyQpDS+KFvDt+hSEvjeFEQ==,type:str]
    SECRET_CEPHFS_POOL_NAME: ENC[AES256_GCM,data:/RjWWjUb97Q=,iv:cmvf1WZrB5iLt1on5HSkxoqGbVsykFlSzq/cR4fURZw=,tag:oceo3vdIgifOsYc5JglXog==,type:str]
    SECRET_CEPHFS_METADATA_POOL_NAME: ENC[AES256_GCM,data:ERcCSru8QH8dVs5c,iv:R6GINGMp8/BYmZBp8sg0V97DYKlVv8tR5dX1cWJWAZM=,tag:Xcw/qMLBBpONyzuByerMVg==,type:str]
    SECRET_CEPHFS_FS_NAME: ENC[AES256_GCM,data:kW98,iv:mpyGvRxBevvJ7AW0Once2IImhBdAnnRc5d+G9j9MlN4=,tag:vIyBm4AxfZmdctUBKW5P6g==,type:str]
    SECRET_CSI_CEPHFS_NODE_SECRET: ENC[AES256_GCM,data:XDsD/poM4Jz4juG66hVteIA5GpcFIN7uCFtEy14EqpjmTKkrFektZQ==,iv:UpRCpydz45PoQtqy2p1w5NKiCKYS6QVGQ0BHiXPTlrw=,tag:a8PbVOKwKMerXdzGPlIl2Q==,type:str]
    SECRET_CSI_CEPHFS_PROVISIONER_SECRET: ENC[AES256_GCM,data:hRpD5861WwTtcOPbWYJx1TZpXjfc7GK+flQj9rKFLByEe7p5xeXnAA==,iv:iG7ChKB41c1tWAGlztBlg0RPzgf1feHVQue5+NHcQd4=,tag:52/cBQr8PPR8myBtH9ojew==,type:str]
    SECRET_CSI_CEPHFS_NODE_SECRET_NAME: ENC[AES256_GCM,data:mdSeM/KvXYcjCYVWaGOJ,iv:7NPbU3ypYqofUY3KLj/myIiHuaXCidb07iqQTZSy8Lk=,tag:oqb2HEj0qf4Ha8LAUepycg==,type:str]
    SECRET_CSI_CEPHFS_PROVISIONER_SECRET_NAME: ENC[AES256_GCM,data:CzW909cZHAkRmoXRakzC7j4mDN5olg==,iv:7ivarULKUtzWn4nrDglHvvBpisuP827xjoOEZY8HdBI=,tag:O9xGjHLsFjZxKyEJ5CHbyA==,type:str]
    SECRET_MONITORING_ENDPOINT: ENC[AES256_GCM,data:CiWkc8ajOS8NRw==,iv:+EDOKAQ6Cm7/xgt29MZiwdt3NcVvgfAaqkl1ORyGXik=,tag:znwpfzl+mWrSVgIsoyy5sA==,type:str]
    #ENC[AES256_GCM,data:uEaVlmI809ywx0gHP6Je8cX6xIquiVHUMv0vpubsIBy8ODm3dw==,iv:ptPmO2f1uFRYQfqM172FM+rwZxLVE23vW3ZUOIwKHTw=,tag:N0ut/O44AD1/L+/GI4nKrA==,type:comment]
    SECRET_RBD_POOL_NAME: ENC[AES256_GCM,data:LJGhEBlyrw==,iv:82U+B+Attgsyv+4iGtnbiAVNAQMokEZ6P8SBFqDjobI=,tag:Q+lNarm+ZtPNeP2lrf6Fjw==,type:str]
    SECRET_RGW_POOL_PREFIX: ENC[AES256_GCM,data:Yc0eDik4aQ==,iv:vyRVqKBbKZIwxR2cYy8ZTcm2W7WzuMQPgUcLgu/kqi4=,tag:/sb4SsLCvQStbZmVyKN/hg==,type:str]
    CEPH1_NODE: ENC[AES256_GCM,data:ZcrNOzozdcL+Tg==,iv:BqhAEXoaI6paa9i84R0T1Lj9L0oGjbxWsXOmrpHVvQA=,tag:pwwHfqgxcxo1im6yYMdWVw==,type:str]
    CEPH2_NODE: ENC[AES256_GCM,data:64p22D6kH1EB6g==,iv:5es5NXBuyaxY++okh+qCy9QS4UmuRL4p/QxeU5hFby0=,tag:xOtwTEsUOSyHCGu5SQDH4Q==,type:str]
    CEPH3_NODE: ENC[AES256_GCM,data:Moztk1T4fwIGsA==,iv:h3yFOUCYZQws877ABQqH8N52klDilkABr1uwz/+MKVs=,tag:iwZXjrUyu/qNw+HbW+9BEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1upzm4g68d6555nfx3mn2xganv72sxyksa939cnlqnj82qaj3aq3sj998ls
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIM3FmUGtETFd6WFNlRWlD
            amFTNk8rdTJxWUd2U2N0MCtPaXB5Rlo3bmxnCmZKcTRvVFFNOTlaTUEvcHlzaUhw
            RVFZbWZ2WlV5dk9XVi9pUTdqQUQ4MEkKLS0tIDJXRy9YL0doNWtEZytnQ2tHMUl1
            d2lOMUFLYm9yRTZPZi9ENVpJWkNaRncKKxyCwebEX7XH1CpZAaAGSdsLwQ9WTW+J
            HDa3XXTuyz+UUFa/yvQbqe0qMttwnbBJAHp+gYJFf7QyttI1naV0eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-10T19:08:40Z"
    mac: ENC[AES256_GCM,data:n0VYrXf+WBXR5c/AgVGzL2Ibf5M//BwIDbEX+0tGA7tfzW9wAanPyFRmRaQHgZvX1qKsunVOLwTlE3XwNH76op8wjvK0kZ2ru2BAuZ2fF5BnmT2zqft72YQrcZ3dh8yoLaJpekbrfojVI9c38LSpwnAFmiHNufgDcjaLDC1VDek=,iv:6E65CJgAtTg0eDdHWPRbNm02jM4QqhX9LLvC+iy1q7c=,tag:mm5mFzClRHnfqPXbLE3wYg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.9.4
