apiVersion: v1
kind: Secret
metadata:
  name: sops-age
stringData:
  age.agekey: ENC[AES256_GCM,data:NU3xkEe3p4z10yhTxaQjaez6oiIsbzTsgID4ElO2KV3qLqcJQjmh5wtJTmJ+Xev36ENwAzioklhoOmSD4ojDSwych/GOc6wJxxex,iv:D/RxHFHiTE1EwYXp5x7QKNU7jQPKNZFJIMtjvZVER7M=,tag:pfq0znPZ5qWZQZ8BTsw69g==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1upzm4g68d6555nfx3mn2xganv72sxyksa939cnlqnj82qaj3aq3sj998ls
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTURhckhyMjZnR1VFUmZT
        a0ZWbzFKeTVNZlJrcFRpMExwZmxiSTVtVTNFCmZWaDZCbkd6YWVVeHlabEVQWVdp
        MEN3OHJLWGRuUW4zK2lzNWZWcTh1c3cKLS0tIDlrR0VFQ05zUFRuTGQ1S1VGREIy
        NmZnbVdjOXMzWEl6VktPc1BmMGpNS1UKFDtkm+umZAee2DsoXTKWueAnB/wvaxUw
        Wh0iysbMc1hlbYOcG75akXXo4s/aOI+Z/+7wMlcwXuOA8Hd028lsew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-12T08:48:33Z"
  mac: ENC[AES256_GCM,data:mSPqJDnfTIf24JHvYiGqSzNwu6YaiOEYgRyyHxa24D5A/ZVkMGmr3GNzZdH9/fqCNB+IgAVtBCBKyMH1UYLMF47gXK40CaATQuyzB6bGAS48d6gyCes0x6uC+agZqJYbCfC4F2ghpw8WO3KlypWt2EP1tcQCRkse8yR+rW7AOkQ=,iv:YKyxD1C9+1MPT2bXqNTjGapOndZ2SxmfStSRiMrjlJw=,tag:IN0zH0qVICaBhN/bXoYnAA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
