---
apiVersion: v1
kind: Secret
type: kubernetes.io/rook
metadata:
  name: rook-csi-rbd-node
  namespace: rook-ceph-external
stringData:
  userID: ${SECRET_CSI_RBD_NODE_SECRET_NAME}
  userKey: ${SECRET_CSI_RBD_NODE_SECRET}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/rook
metadata:
  name: rook-csi-rbd-provisioner
  namespace: rook-ceph-external
stringData:
  userID: ${SECRET_CSI_RBD_PROVISIONER_SECRET_NAME}
  userKey: ${SECRET_CSI_RBD_PROVISIONER_SECRET}
