---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    remediation:
      retries: -1
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      home-assistant:
        containers:
          home-assistant:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2025.6.1
          code:
            dependsOn: home-assistant
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.101.1
            args:
              - --auth
              - "none"
              - --user-data-dir
              - "/config/.vscode"
              - --extensions-dir
              - "/config/.vscode"
              - --port
              - "8081"
              - "/config"
        initContainers:
          ensure-config:
            image:
              repository: busybox
              tag: latest
            command:
              - /bin/sh
              - -c
              - |
                CONFIG_FILE="/config/configuration.yaml"
                if ! grep -q "trusted_proxies" "$CONFIG_FILE"; then
                  echo "Adding missing http settings..."
                  echo "" >> "$CONFIG_FILE"
                  echo "http:" >> "$CONFIG_FILE"
                  echo "  use_x_forwarded_for: true" >> "$CONFIG_FILE"
                  echo "  trusted_proxies:" >> "$CONFIG_FILE"
                  echo "    - 10.42.0.0/16" >> "$CONFIG_FILE"
                fi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        ports:
          http:
            port: &port 8123
    route:
      app:
        hostnames:
          - "{{ .Release.Name }}.anneken.cloud"
          - hass.anneken.cloud
        parentRefs:
          - name: external
            namespace: kube-system
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: home-assistant
        globalMounts:
          - path: /config
      config-cache:
        existingClaim: home-assistant-cache
        advancedMounts:
          home-assistant:
            app:
              - path: /venv
                subPath: hass-venv
      tmpfs:
        type: emptyDir
        advancedMounts:
          home-assistant:
            app:
              - path: /config/logs
                subPath: logs
              - path: /config/tts
                subPath: tts
              - path: /tmp
                subPath: tmp
