---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: databases
  annotations:
    io.cilium/lb-ipam-ips: 10.10.0.60
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres-immich
    role: primary
