---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-automation-wyoming-services
  namespace: flux-system
spec:
  interval: 30m
  path: "./kubernetes/apps/default/wyoming-services/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  postBuild:
    substituteFrom: []
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph-external
